site_name: Jounin lappujuoksut
site_url: https://emick.github.io/blog-to-wiki-demo

docs_dir: wiki
theme:
  name: material
  language: fi
  features:
    - navigation.indexes
    - navigation.sections
    - navigation.tabs

plugins:
  - search:
      lang: fi
